run:
  timeout: 3m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - gofmt
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
